### PR TITLE
log user out on expired refreshToken

### LINKED ISSUE #11: Login broken on refreshToken expiry
Hi John,

think logout should be forced from `axios-auth-interceptor.refreshAuthLogic()` when 401 is returned from the api, indicating expired refreshToken. Otherwise client needs to manually nuke their localStorage to be able to continue - without doing so the web client will forever try to refresh the access token that will never succeed.

### PR DESCRIPTION
**Pull request by laur89**
- currently access token renewal flow is broken when refreshToken has expired;
  refreshAuthLogic() in axios-auth-interceptor would try to renew access token, but
  a) because token is expired, it gets 401 in response; and
  b) because refreshAuthLogic() uses the same axios instance for refresh call, then
     40x responses all hang, ie refreshAuthLogic() effectively hangs whenever 401
     is responded from the api due to token expiry.

- this change:
  a) introduces a separate axios instance for token renewal calls (see
     https://stackoverflow.com/questions/65789806/axios-dosent-catch-error-with-axios-auth-refresh-library )
  b) enforces logout if refreshAuthLogic() fails; most likely reason for this failure
     would be a 401 response from the api, caused by refreshToken expiry.

Fix #11

### CODE REVIEW

File: src/store/user/index.ts [hunk 1]
```diff
@@ -107,9 +108,16 @@ const actions: ActionTree<UserState, RootState> = {
   },
   async logout({ commit, dispatch, state }: UserContext): Promise<void> {
     try {
-      commit(CLEAR_USER);
+      await commit(CLEAR_USER);
```
Comment (johndatserakis) [inline src/store/user/index.ts:111]: This `await` is unneeded.

**Review by johndatserakis — APPROVED** [review]
🙏 Thank you for this.

Looks great and worked well in my testing. Just one comment.

Much appreciated.
